import:
  - ~/.config/alacritty/catppuccin-mocha.yml

window:
  padding:
    x: 10
    y: 10
  class:
    instance: Alacritty
    general: Alacritty
  opacity: 0.9

scrolling:
  history: 10000
  multiplier: 3


font:
  normal:
    family: JetBrains Mono Nerd Font
    style:  Bold
  bold:
    family: JetBrains Mono Nerd Font
    style:  Bold
  italic:
    family: JetBrains Mono Nerd Font
    style:  MediumItalic
  bold_italic:
    family: JetBrains Mono Nerd Font
    style: BoldItalic
  size: 10
draw_bold_text_with_bright_colors: true


selection:
  save_to_clipboard: false

key_bindings:
  - { key: Return, mods: Super|Shift, action: SpawnNewInstance }
